KWEBofficial/stylevillage-server

- src/common/enum/category.enum.ts
- src/common/enum/season.enum.ts
- src/common/enum/status.enum.ts
- src/entity/clothes.entity.ts
season, status, category enum 생성하고 clothes entity 만들었습니다
enum 내 값은 제가 일단 임의로 설정했고 나중에 바꿔야할 것 같습니다
> feat: add clothes entity

- src/entity/apply.entity.ts
> apply entity 생성했습니다.

- src/common/enum/status.enum.ts
- src/entity/clothes.entity.ts
clothes entity에서 status import를 하지 못해 생기는 에러를 해결하였습니다.
> clothes error 해결

- src/controller/clothes/controller.ts
- src/controller/clothes/router.ts
- src/controller/router.ts
- src/entity/clothes.entity.ts
- src/repository/clothes.repository.ts
- src/service/clothes.service.ts
- src/type/clothes/createClothes.req.ts
- src/type/clothes/createClothes.res.ts
> 옷생성 api 추가

- src/controller/closet/controller.ts
- src/controller/closet/router.ts
- src/controller/router.ts
- src/repository/closet.repository.ts
- src/service/closet.service.ts
- src/type/closet/closet.ts
- src/type/closet/postCloset.req.ts
- src/type/closet/postCloset.res.ts
옷장 생성 api 추가했습니다
name을 request body로 받아서 name을 200OK 시 name을 result로 보내줍니다.
다음과 같이 실행 확인했습니다.
옷장 이름 미입력 시 에러 처리하였습니다.
> feat: add post closet api

- src/controller/clothes/controller.ts
- src/controller/clothes/router.ts
- src/repository/clothes.repository.ts
- src/service/clothes.service.ts
- src/type/clothes/modifyClothes.req.ts
- src/type/clothes/modifyClothes.res.ts
옷 수정 api 추가했습니다. enum 검사 로직은 비워두었고, enum 검사 util 추가하는 브랜치에서 작업하겠습니다
> feat: modify clothes api

- src/controller/closet/controller.ts
- src/controller/closet/router.ts
- src/repository/closet.repository.ts
- src/service/closet.service.ts
- src/type/closet/modifyCloset.req.ts
- src/type/closet/modifyCloset.res.ts
옷장 수정 api 입니다.
param으로 closetid, body로 변경할closetname을 받고, 수정 성공 시 message를 응답합니다.
name이 없을 경우 에러를 발생 시킵니다.
자신의 옷장이 아닐 경우 에러를 발생 시킵니다.
테스트 화면입니다.
> feat: modify-closet-api

- src/controller/closet/controller.ts
- src/controller/clothes/controller.ts
- src/type/closet/modifyCloset.res.ts
- src/type/closet/postCloset.res.ts
- src/type/clothes/createClothes.res.ts
- src/type/clothes/modifyClothes.res.ts
- src/type/default.res.ts
default response 타입을 따로 만들었습니다.
> feat: add default response

- src/controller/closet/controller.ts
- src/controller/closet/router.ts
- src/repository/closet.repository.ts
- src/service/closet.service.ts
- src/type/closet/getClosetList.res.ts
옷장 리스트 가져오기 API를 새로 만들었습니다. Param이나 Request Body는 없고 다음과 같이 id, name의 리스트를 반환합니다.
> feat: add get closet list api

- src/controller/clothes/controller.ts
- src/controller/clothes/router.ts
- src/service/clothes.service.ts
옷 삭제하기 api입니다.
파라미터로 clothesId를 받아 삭제를 성공하면 성공 message를 응답합니다.
> feat: add delete-clothes-api

- src/service/clothes.service.ts
closetId -> clothesId
옷 아이디에 해당하는 변수가 closetId로 되어있어 clothesId로 변경하였습니다.
> refactor: modifyClothes서비스의 변수명 변경

- src/controller/clothes/controller.ts
- src/entity/clothes.entity.ts
- src/repository/clothes.repository.ts
- src/repository/user.repository.ts
- src/service/apply.service.ts
- src/service/clothes.service.ts
- src/type/clothes/Clothes.ts
- src/type/clothes/getClothes.res.ts
clothes entity를 수정했습니다.
owner column을 추가하고, closet column을 nullable로 수정하였습니다.
그에 따라 clothes.closet.owner.id -> clothes.owner.id로 수정하였습니다.
추가로 clothes repository에 잘못 쓰인 코드를 발견하여 수정하였습니다.
> fix: clothes entity

- src/controller/clothes/controller.ts
- src/entity/clothes.entity.ts
- src/repository/clothes.repository.ts
- src/repository/user.repository.ts
- src/service/apply.service.ts
- src/service/clothes.service.ts
- src/type/clothes/Clothes.ts
- src/type/clothes/getClothes.res.ts
다슬님이 작업하신 clothes,closet 변경 브랜치를 기반으로 생성한 PR입니다
> Fix:is my closet in clothes

- src/controller/lend/controller.ts
- src/controller/lend/router.ts
- src/repository/lend.repository.ts
- src/service/lend.service.ts
- src/type/lend/getLends.res.ts
> feat:get-my-lends-api

- src/controller/review/controller.ts
- src/controller/review/router.ts
- src/repository/closet.repository.ts
- src/repository/lend.repository.ts
- src/service/apply.service.ts
- src/service/closet.service.ts
- src/service/lend.service.ts
> mod: allow duplicate closet name

- src/controller/apply/controller.ts
- src/controller/apply/router.ts
- src/controller/lend/controller.ts
- src/controller/lend/router.ts
- src/controller/router.ts
- src/service/apply.service.ts
- src/service/lend.service.ts
- src/type/apply/createApply.req.ts
- src/type/lend/createLend.req.ts
createLend수정 및 createApply 생성
approveApply, rejectApply는 사용목적상 /lend -> /apply로 변경
그리고 clothes.closet.owner로 찾아가던 코드 clothes.owner로 변경했습니다.
> createApply생성 및 여러가지 수정입니다.

- src/controller/review/controller.ts
- src/controller/review/router.ts
- src/controller/router.ts
- src/repository/lend.repository.ts
- src/service/lend.service.ts
> feat:modify-review-api

- src/repository/lend.repository.ts
- src/service/apply.service.ts
- src/service/clothes.service.ts
- src/type/clothes/getClothes.res.ts
- src/type/lend/review.res.ts
옷 상세 가져오기를 하면 리뷰도 같이 불러오도록 수정하였습니다.
> fix: add review to get-clothes-api

- src/controller/clothes/controller.ts
- src/entity/clothes.entity.ts
- src/repository/lend.repository.ts
- src/repository/wish.repository.ts
- src/service/auth.service.ts
- src/service/clothes.service.ts
- src/service/wish.service.ts
- src/type/clothes/Clothes.ts
- src/type/clothes/createClothes.req.ts
- src/type/clothes/getClosetClothes.ts
- src/type/clothes/getClothes.res.ts
- src/type/clothes/modifyClothes.req.ts
- src/type/user/login.res.ts
옷 설명이 필요할 거 같아 clothes 관련 api에 모두 추가했습니다.
로그인 반환 값으로 아이디 있으면 좋을 거 같아서 추가했고 옷 상세에 reviewer 정보가 안 떠서 수정했습니다.
> feat: add description to clothes

- src/controller/clothes/controller.ts
- src/controller/clothes/router.ts
- src/entity/clothes.entity.ts
- src/repository/clothes.repository.ts
- src/repository/wish.repository.ts
- src/service/clothes.service.ts
- src/type/clothes/getClothes.res.ts
- src/type/clothes/getClothesList.res.ts
GET `/clothes/popular/:count`
예시 res)
추가적으로 옷 상세 가져오기에 wishCount를 추가했습니다.
> 인기있는 옷 리스트 가져오기

- src/controller/user/controller.ts
- src/controller/user/router.ts
> feat: get user profile by id

- src/controller/clothes/controller.ts
- src/controller/clothes/router.ts
- src/repository/clothes.repository.ts
- src/repository/user.repository.ts
- src/service/clothes.service.ts
- src/type/clothes/getClothesList.res.ts
로그인된 사용자와 조회하는 사용자가 같을 경우 isOpen이 false인 옷도 가져올 수 있도록 했습니다.
isWished 필드 또한 가져오도록 했습니다.
> 사용자 id를 통해 옷 목록 가져오기

- src/entity/clothes.entity.ts
image url이 길어 varchar -> text로 type 변경
> clothes image column text로 변경

- src/repository/lend.repository.ts
내 대여 목록 가져오기 api에서 clothes 정보가 얻어지지 않는 문제가 생겨 레포지토리 수정해서 해결하였습니다.
> fix/clothes 반환 안되는 문제 해결

- src/controller/apply/controller.ts
- src/controller/apply/router.ts
- src/repository/apply.repository.ts
- src/service/apply.service.ts
- src/type/apply/getSendedApply.res copy.ts
> feat: 대여 신청 내역 가져오기 api
